import Phaser from 'phaser';import './styles.css';import {BootScene} from './scenes/BootScene';import {GameScene} from './scenes/GameScene';import {gameSocket} from './net/socket';import {VirtualControls} from './input/VirtualControls';import type {GameSnapshot} from './types';
const ui=document.querySelector<HTMLDivElement>('#ui')!;let controls:VirtualControls|undefined;let lastRevision=-1;let resetTimer=0;
new Phaser.Game({type:Phaser.AUTO,parent:'game',width:960,height:540,backgroundColor:'#101427',scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},render:{antialias:true,pixelArt:false},scene:[BootScene,GameScene]});
function menu(){controls?.destroy();controls=undefined;ui.innerHTML=`<main class="screen"><section class="card"><h1 class="logo">别丢下我</h1><p class="tag">两块方块，一条路。横屏邀请好友一起闯关。</p><button id="create">创建房间</button><div class="row"><input id="code" maxlength="4" inputmode="numeric" placeholder="房间码"><button id="join" class="secondary">加入</button></div><p class="error" id="error"></p></section></main>`;const code=ui.querySelector<HTMLInputElement>('#code')!;code.value=new URLSearchParams(location.search).get('room')??'';ui.querySelector('#create')!.addEventListener('click',async()=>{const a=await gameSocket.create();a.ok?waiting(a.roomCode!):error(a.error)});ui.querySelector('#join')!.addEventListener('click',async()=>{const a=await gameSocket.join(code.value);a.ok?(a.snapshot?.players.length===2?playing(a.snapshot):waiting(a.roomCode!)):error(a.error)});}
function error(msg='操作失败'){ui.querySelector('#error')!.textContent=msg}
function waiting(code:string){const link=`${location.origin}${location.pathname}?room=${code}`;ui.innerHTML=`<main class="screen"><section class="card"><p>房间码</p><div class="room-code">${code}</div><p class="pulse">等待好友加入...</p><div class="row"><button id="copy">复制邀请链接</button><button id="back" class="secondary">返回</button></div><p class="error"></p></section></main>`;ui.querySelector('#copy')!.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(link);ui.querySelector('.error')!.textContent='邀请链接已复制'}catch{ui.querySelector('.error')!.textContent=link}});ui.querySelector('#back')!.addEventListener('click',leave);}
function playing(s:GameSnapshot){if(!ui.querySelector('.hud')){ui.innerHTML=`<div class="hud"><div class="hud-top"><span id="level"></span><span>房间 ${s.roomCode}</span><button id="leave">返回首页</button></div><div id="status" class="status" hidden></div><div id="control-root"></div></div>`;ui.querySelector('#leave')!.addEventListener('click',leave);controls=new VirtualControls(ui.querySelector('#control-root')!,state=>gameSocket.input(state));}updateHud(s)}
function updateHud(s:GameSnapshot){ui.querySelector('#level')!.textContent=`第 ${s.level+1} 关 · ${s.levelName}`;const status=ui.querySelector<HTMLElement>('#status')!;if(s.complete){controls?.destroy();controls=undefined;ui.innerHTML=`<main class="screen"><section class="card"><h1 class="logo">通关成功</h1><p class="tag">你们真的没有丢下彼此。</p><div class="row"><button id="again">再来一局</button><button id="home" class="secondary">返回首页</button></div></section></main>`;ui.querySelector('#again')!.addEventListener('click',()=>gameSocket.restart());ui.querySelector('#home')!.addEventListener('click',leave);return}let msg=s.paused?'等待队友重连':'';if(s.resetMessage&&s.revision!==lastRevision){msg=s.resetMessage;clearTimeout(resetTimer);resetTimer=window.setTimeout(()=>{status.hidden=true},1000)}lastRevision=s.revision;status.textContent=msg;status.hidden=!msg;}
function leave(){gameSocket.leave();history.replaceState({},'',location.pathname);menu()}
gameSocket.addEventListener('state',(e)=>{const s=(e as CustomEvent<GameSnapshot>).detail;if(s.players.length<2)waiting(s.roomCode);else playing(s)});gameSocket.addEventListener('closed',()=>{menu();error('房间已过期')});window.addEventListener('contextmenu',e=>e.preventDefault());document.addEventListener('gesturestart',e=>e.preventDefault());menu();
