import {randomBytes} from 'node:crypto';import type {PlayerId,PlayerState,Room} from './types';import {levels} from './levels';
const blankInput=()=>({left:false,right:false,jump:false});
export class RoomManager{
 rooms=new Map<string,Room>();
 create(socketId:string){let code='';do{code=String(Math.floor(1000+Math.random()*9000))}while(this.rooms.has(code));const room:Room={code,players:new Map(),level:0,buttons:new Map(),doors:new Map(),keys:new Map(),latchedDoors:new Set(),paused:true,complete:false,revision:0};room.players.set('p1',this.player('p1',socketId));this.rooms.set(code,room);this.reset(room,false);return {room,player:room.players.get('p1')!}}
 join(code:string,socketId:string){const room=this.rooms.get(code);if(!room)throw new Error('房间不存在');if(room.players.size>=2)throw new Error('房间已满');const p=this.player('p2',socketId);room.players.set('p2',p);room.paused=false;this.reset(room,false);return {room,player:p}}
 reconnect(code:string,sessionId:string,socketId:string){const room=this.rooms.get(code);if(!room)return;const player=[...room.players.values()].find(p=>p.sessionId===sessionId);if(!player)return;player.socketId=socketId;player.connected=true;player.input=blankInput();if(room.cleanupTimer)clearTimeout(room.cleanupTimer);room.cleanupTimer=undefined;room.paused=room.players.size<2||[...room.players.values()].some(p=>!p.connected);return {room,player}}
 disconnect(socketId:string){for(const room of this.rooms.values()){const p=[...room.players.values()].find(x=>x.socketId===socketId);if(!p)continue;p.connected=false;p.input=blankInput();room.paused=true;if(room.cleanupTimer)clearTimeout(room.cleanupTimer);room.cleanupTimer=setTimeout(()=>{this.rooms.delete(room.code)},60_000);return room}}
 leave(code:string,socketId:string){const room=this.rooms.get(code);if(!room)return;const p=[...room.players.entries()].find(([,x])=>x.socketId===socketId);if(p)room.players.delete(p[0]);if(room.players.size===0)this.rooms.delete(code);else room.paused=true;return room}
 reset(room:Room,message=true){const level=levels[room.level];room.buttons=new Map(level.buttons.map(x=>[x.id,false]));room.doors=new Map(level.doors.map(x=>[x.id,false]));room.keys=new Map(level.keys.map(x=>[x.id,false]));room.latchedDoors.clear();for(const [id,p] of room.players){const s=level.spawn[id];Object.assign(p,{x:s.x,y:s.y,vx:0,vy:0,onGround:false,atExit:false,input:blankInput()})}room.revision++;room.resetMessage=message?'本关重置':''}
 snapshot(room:Room){return {roomCode:room.code,level:room.level,levelName:levels[room.level].name,players:[...room.players.values()].map(({id,x,y,w,h,connected,atExit})=>({id,x,y,w,h,connected,atExit})),doors:[...room.doors].map(([id,open])=>({id,open})),buttons:[...room.buttons].map(([id,pressed])=>({id,pressed})),keys:[...room.keys].map(([id,collected])=>({id,collected})),paused:room.paused,complete:room.complete,revision:room.revision,resetMessage:room.resetMessage}}
 private player(id:PlayerId,socketId:string):PlayerState{return {id,x:0,y:0,w:32,h:44,vx:0,vy:0,onGround:false,connected:true,socketId,sessionId:randomBytes(18).toString('hex'),input:blankInput(),atExit:false}}
}
